### ISSUE TITLE
Pas de visualisation de l'ensemble des questions lors de la recherche

### ISSUE THREAD

**Issue by OprahN** [OprahN/GL02_TC_Forever#8]
Ce qu'on veut faire, c'est pourvoir avoir l'ensemble des questions afin d'en sélectionner un pour visualisation

**Comment by ktiass** [comment]
![image](https://github.com/OprahN/GL02_TC_Forever/assets/64667821/8c8840ff-3603-4e2b-8e09-489cd01618ad)
